config/routes.rb
Rails.application.routes.draw do
  root to: 'user#index'

  resources :user
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.create
    redirect_to edit_user_path(@user.id)
  end

  def edit
    @user = User.find_by(id: params[:id])
    @user.valid? if @user.created_at != @user.updated_at
  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Untitled
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-dark.bg-dark{:style => "background-color: #e3f2fd;"}
      .container
        = link_to 'PartingPro', root_path, class: 'navbar-brand'

    .container
      = yield

app/views/user/_form.html.haml
.row
  .col-2
  .col-8
    .pt-5
      = simple_form_for(user,
                        url: '#' ) do |f|
        .row
          .col-12.col-lg-6.mb-3.pt-2
            = f.input :first_name, class: 'form-control'

          .col-12.col-lg-6.mb-3.pt-2
            = f.input :last_name, class: 'form-control'

        .mb-2.pt-2
          = f.input :middle_name, class: 'form-control'

        .row
          .col-12.col-lg-6.mb-3.pt-2
            = f.input :phone_number, class: 'form-control'

          .col-12.col-lg-6.mb-3.pt-2
            = f.input :email, class: 'form-control'

        .mb-2.pt-2
          = f.input :social_security_number, class: 'form-control'

        .mb-2.pt-2
          = f.input :country, as: :select, required: false,
                collection: ['United States', 'Other'], include_blank: false,
                selected: f.object.country ? f.object.country : 'United States',
                input_html: { class: 'form-select' }

        .mb-2.pt-2
          = f.input :address, class: 'form-control'
        .row
          .col-12.col-lg-6.mb-3.pt-2
            = f.input :city, class: 'form-control'

          .col-12.col-lg-6.mb-3.pt-2
            = f.input :state, class: 'form-control'

        .mb-2.pt-2
          = f.input :zip_code, label: "Zip code", class: 'form-select'

    .mb-2.text-end
      = link_to 'Back', root_path, class: 'button btn btn-primary'

app/views/user/edit.html.haml
= render partial: 'user/form', locals: { user: @user}

app/views/user/index.html.haml
.pt-5
.container
  .pt-2.text-end
    = link_to 'Create User', new_user_path, class: 'btn btn-primary'
  %table.table
    %thead
      %tr
        %th{:scope => "col"} #
        %th{:scope => "col"} First name
        %th{:scope => "col"} Last name
        %th{:scope => "col"} email
        %th{:scope => "col"}
    %tbody
      - @users.each do |user|
        %tr
          %th{:scope => "row"} 1
          %td= user.first_name
          %td= user.last_name
          %td= user.email
          %td.text-end.pe
            %span
              = link_to 'Edit', edit_user_path(user), class: 'btn btn-outline-info me-3'
              = link_to 'Remove', '#', class: 'button btn btn-outline-danger'